print("### CELL 0 START", flush=True)
import pandas as pd

df = pd.read_csv("data/customer_churn.csv")
df.head()
print("### CELL 0 DONE", flush=True)
print("### CELL 2 START", flush=True)
df["Churn"].value_counts()
print("### CELL 2 DONE", flush=True)
print("### CELL 3 START", flush=True)
df.info()
print("### CELL 3 DONE", flush=True)
print("### CELL 4 START", flush=True)
df.shape
print("### CELL 4 DONE", flush=True)
print("### CELL 5 START", flush=True)
df.columns
print("### CELL 5 DONE", flush=True)
print("### CELL 6 START", flush=True)
df.isnull().sum()
print("### CELL 6 DONE", flush=True)
print("### CELL 7 START", flush=True)
df["Churn"].value_counts()
print("### CELL 7 DONE", flush=True)
print("### CELL 8 START", flush=True)
df["Churn"].value_counts(normalize=True) * 100

print("### CELL 8 DONE", flush=True)
print("### CELL 9 START", flush=True)
df["Contract"].unique()
print("### CELL 9 DONE", flush=True)
print("### CELL 10 START", flush=True)
df.dtypes
print("### CELL 10 DONE", flush=True)
print("### CELL 11 START", flush=True)
print("hib")
print("### CELL 11 DONE", flush=True)
print("### CELL 12 START", flush=True)
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
print("### CELL 12 DONE", flush=True)
print("### CELL 13 START", flush=True)
df.isnull().sum()
print("### CELL 13 DONE", flush=True)
print("### CELL 14 START", flush=True)
df = df.dropna()
print("### CELL 14 DONE", flush=True)
print("### CELL 15 START", flush=True)
df = df.drop("customerID", axis=1)
print("### CELL 15 DONE", flush=True)
print("### CELL 16 START", flush=True)
df.info()
print("### CELL 16 DONE", flush=True)
print("### CELL 17 START", flush=True)
import matplotlib.pyplot as plt
import seaborn as sns
print("### CELL 17 DONE", flush=True)
print("### CELL 18 START", flush=True)
sns.countplot(x="Churn", data=df)
plt.title("Customer Churn Count")
plt.show()
print("### CELL 18 DONE", flush=True)
print("### CELL 19 START", flush=True)
sns.countplot(x="Contract", hue="Churn", data=df)
plt.title("Contract Type vs Churn")
plt.xticks(rotation=15)
plt.show()
print("### CELL 19 DONE", flush=True)
print("### CELL 20 START", flush=True)
sns.countplot(x="InternetService", hue="Churn", data=df)
plt.title("Internet Service vs Churn")
plt.show()
print("### CELL 20 DONE", flush=True)
print("### CELL 21 START", flush=True)
plt.figure(figsize=(8,5))
sns.histplot(df["MonthlyCharges"], bins=30, kde=True)
plt.title("Monthly Charges Distribution")
plt.show()
print("### CELL 21 DONE", flush=True)
print("### CELL 22 START", flush=True)
plt.figure(figsize=(8,5))
sns.histplot(df["MonthlyCharges"], bins=30, kde=True)
plt.title("Monthly Charges Distribution")
plt.show()
print("### CELL 22 DONE", flush=True)
print("### CELL 23 START", flush=True)
plt.figure(figsize=(8,5))
sns.boxplot(x="Churn", y="MonthlyCharges", data=df)
plt.title("Monthly Charges vs Churn")
plt.show()
print("### CELL 23 DONE", flush=True)
print("### CELL 24 START", flush=True)
plt.figure(figsize=(8,5))
sns.boxplot(x="Churn", y="tenure", data=df)
plt.title("Tenure vs Churn")
plt.show()
print("### CELL 24 DONE", flush=True)
print("### CELL 25 START", flush=True)
X = df.drop("Churn", axis=1)
y = df["Churn"]
y = y.map({"No": 0, "Yes": 1})
X = pd.get_dummies(X, drop_first=True)
print("### CELL 25 DONE", flush=True)
print("### CELL 26 START", flush=True)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)
print("### CELL 26 DONE", flush=True)
print("### CELL 27 START", flush=True)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print("### CELL 27 DONE", flush=True)
print("### CELL 28 START", flush=True)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("### CELL 28 DONE", flush=True)
print("### CELL 29 START", flush=True)
from sklearn.linear_model import LogisticRegression
print("### CELL 29 DONE", flush=True)
print("### CELL 30 START", flush=True)
model = LogisticRegression(max_iter=1000)
print("### CELL 30 DONE", flush=True)
print("### CELL 31 START", flush=True)
model.fit(X_train, y_train)
print("### CELL 31 DONE", flush=True)
print("### CELL 32 START", flush=True)
y_pred = model.predict(X_test)
print("### CELL 32 DONE", flush=True)
print("### CELL 33 START", flush=True)
print(y_pred[:10])
print("### CELL 33 DONE", flush=True)